### PR TITLE
Fixed requirements.txt

### PR DESCRIPTION
**Pull request by JimmyWhitaker**
Pillow requirement needed an extra `=`, and the numpy version was updated to fix:
```
pandas 1.1.1 requires numpy>=1.15.4, but you'll have numpy 1.14.5 which is incompatible.
```

### CODE REVIEW

**Comment by jpatrickpark** [comment]
The required version of pandas is 0.22.0, and it does not have the requirement of `numpy>=1.15.4`.

It seems that this became an issue after pandas library released newer versions which require higher versions of numpy.

To handle this issue, we can either (1) prevent installation of newer version of pandas (by setting the upper limit of version) or (2) adjust numpy version requirement like @JimmyWhitaker suggested. If this is a product under active development it might make sense to do (2). However, to make sure our code works as expected without any breaking changes in the newer versions of these libraries (although it would be unlikely), I think (1) would be a safer option.

And `=` is indeed not a valid operator, we should change it to `==`.

**Comment by JimmyWhitaker** [comment]
If it helps with reproducibility of the code, this is the Dockerfile that I used to build the code and execute it on Kubernetes with Pachyderm:
```
FROM pytorch/pytorch:0.4.1-cuda9-cudnn7-devel

RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

WORKDIR /workspace
COPY . /workspace
RUN pip install --upgrade pip && pip install -r requirements.txt
```

**Comment by jpatrickpark** [comment]
We will close this pull request for now since (1) we haven't decided if we should upgrade the version requirements and (2) irrelevant commits are starting to become associated with the request. We will fix the syntax error of requirements.txt when we update the repo.

**Comment by JimmyWhitaker** [comment]
I just realized that I accidentally pushed to the branch that I had opened the PR with. Really sorry about that.  I'll revert that if you wanted to pull the syntax issue alone.

**Pull request closed without merging**
